### ISSUE TITLE
Is it possible to ping GA3 and GA4 at the same time without having to send data twice, separately? 

### ISSUE THREAD

**Issue by abbyblachman** [bbeckford/google_analytics_4_serverside_event_tracker#1]
Just curious if you know of a way to do this for server side event tracking!

**Comment by bbeckford** [comment]
You'd have to do 2 separate requests, but technically you don't have to wait for the requests to complete.

I would suggest keeping the methods separated anyway as you'll probably drop Universal Analytics in future.

I'd recommend this for Universal Analytics:

https://gist.github.com/chrisblakley/e1f3d79b6cecb463dd8a
